# Site settings
title: Ritchie Jacobs
tagline: Front-end Developer
description: >-
  Articles, tips and tricks on the latest front-end topics like Angular, CSS3 and HTML5.
paginate: 5
paginate_path: "/page:num/"
permalink: /:title

GA_TRACKING_ID: "UA-42577887-5"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Assets
sass:
  sass_dir: _sass
  style: :compressed

collections:
  tag:
    output: true

defaults:
  -
    scope:
      path: ""
      type: tag
    values:
      layout: "tag"
